name: CustomGlowAPI
main: me.marquez.cgapi.CustomGlowPlugin
version: ${version}
api-version: ${minecraft.version}
depend: [ProtocolLib]
author: DevMarquez
website: https://github.com/Marquez77/CustomGlowAPI